version: '3.8'

services:
  # -------------------
  # BANCOS DE DADOS
  # -------------------
  produtos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: produtos
    ports:
      - "5433:5432"
    volumes:
      - produtos_data:/var/lib/postgresql/data

  usuarios-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: usuarios
    ports:
      - "5434:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data

  pagamentos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pagamentos
    ports:
      - "5435:5432"
    volumes:
      - pagamentos_data:/var/lib/postgresql/data

  pedidos-db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - pedidos_data:/data/db

  # -------------------
  # MICRO SERVIÇOS
  # -------------------
  api-produtos:
    build: ./api-produtos
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:pass@produtos-db:5432/produtos"
      PORT: 3001
    depends_on:
      - produtos-db

  api-usuarios:
    build: ./api-usuarios
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://user:pass@usuarios-db:5432/usuarios"
      PORT: 3002
    depends_on:
      - usuarios-db

  api-pagamentos:
    build: ./api-pagamentos
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgresql://user:pass@pagamentos-db:5432/pagamentos"
      MONGO_URL: "mongodb://pedidos-db:27017/pedidos"
      PORT: 3003
    depends_on:
      - pagamentos-db
      - pedidos-db

  api-pedidos:
    build: ./api-pedidos
    ports:
      - "3004:3004"
    environment:
      MONGO_URL: "mongodb://pedidos-db:27017/pedidos"
      PORT: 3004
    depends_on:
      - pedidos-db
      - api-produtos
      - api-usuarios

volumes:
  produtos_data:
  usuarios_data:
  pagamentos_data:
  pedidos_data:
