services:
  # -------------------
  # BANCOS DE DADOS
  # -------------------
  produtos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: produtos
    ports:
      - "5433:5432"
    volumes:
      - produtos_data:/var/lib/postgresql/data

  usuarios-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: usuarios
    ports:
      - "5434:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data

  pagamentos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pagamentos
    ports:
      - "5435:5432"
    volumes:
      - pagamentos_data:/var/lib/postgresql/data

  pedidos-db:
    image: mongo:6
    container_name: pedidos-db
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pedidos
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - pedidos_data:/data/db
      - ./api-pedidos/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


  # -------------------
  # MICRO SERVIÇOS
  # -------------------
  api-produtos:
    build: ./api-produtos
    expose:
      - "3001"
    environment:
      DATABASE_URL: "postgresql://user:pass@produtos-db:5432/produtos"
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      PORT: 3001
    depends_on:
      - produtos-db
      - redis-cache

  api-usuarios:
    build: ./api-usuarios
    expose:
      - "3002"
    environment:
      DATABASE_URL: "postgresql://user:pass@usuarios-db:5432/usuarios"
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      PORT: 3002
    depends_on:
      - usuarios-db
      - redis-cache

  api-pagamentos:
    build: ./api-pagamentos
    expose:
      - "3003"
    environment:
      DATABASE_URL: "postgresql://user:pass@pagamentos-db:5432/pagamentos"
      MONGO_URL: "mongodb://user:pass@pedidos-db:27017/pedidos?authSource=pedidos"
      ORDER_API_URL: "http://api-pedidos:3004"
      PORT: 3003
    depends_on:
      - pagamentos-db
      - pedidos-db

  api-pedidos:
    build: ./api-pedidos
    expose:
      - "3004"
    environment:
      MONGO_URL: "mongodb://user:pass@pedidos-db:27017/pedidos?authSource=pedidos"
      PORT: 3004
    depends_on:
      - pedidos-db
      - api-produtos
      - api-usuarios
  
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb-init/init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  k6:
    image: grafana/k6:latest
    container_name: k6_runner
    depends_on:
      - api-produtos
      - api-usuarios
      - api-pagamentos
      - api-pedidos
      - influxdb
    volumes:
      - ./k6-scripts:/scripts
    entrypoint: ["k6"]
    networks:
      - default
# === KONG API GATEWAY ===
  kong-db:
    image: postgres:15
    container_name: kong_db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong_password
      POSTGRES_DB: kong
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  kong-migration:
    image: kong:3.4
    container_name: kong_migration
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
    command: "kong migrations bootstrap"
    depends_on:
      - kong-db

  kong-gateway:
    image: kong:3.4
    container_name: kong_gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-migration

  konga:
    image: pantsel/konga
    container_name: konga_ui
    restart: always
    environment:
      NODE_ENV: development
      KONGA_KONG_ADMIN_URL: http://kong-gateway:8001
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway

  api-notifica:
    build: ./api-notifica
    container_name: api-notifica
    environment:
      PORT: 3005
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
    command: node ./index.js

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  # === KAFKA ===
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
  
  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_lab
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    depends_on:
      - redis-cache

  kong-bootstrap:
    image: curlimages/curl:latest
    container_name: kong-bootstrap
    depends_on:
      - kong-gateway
    volumes:
      - ./kong/bootstrap.sh:/bootstrap.sh:ro
    entrypoint: ["/bin/sh", "/bootstrap.sh"]
   
  

volumes:
  produtos_data:
  usuarios_data:
  pagamentos_data:
  pedidos_data:
  influxdb_data:
  grafana_data:
  redis_data:
  kong_postgres_data: