version: '3.8'

services:
  # -------------------
  # BANCOS DE DADOS
  # -------------------
  produtos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: produtos
    ports:
      - "5433:5432"
    volumes:
      - produtos_data:/var/lib/postgresql/data

  usuarios-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: usuarios
    ports:
      - "5434:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data

  pagamentos-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pagamentos
    ports:
      - "5435:5432"
    volumes:
      - pagamentos_data:/var/lib/postgresql/data

  pedidos-db:
    image: mongo:6
    container_name: pedidos-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo-data:/data/db
      - ./api-pedidos/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # -------------------
  # MICRO SERVIÇOS
  # -------------------
  api-produtos:
    build: ./api-produtos
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:pass@produtos-db:5432/produtos"
      PORT: 3001
    depends_on:
      - produtos-db

  api-usuarios:
    build: ./api-usuarios
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://user:pass@usuarios-db:5432/usuarios"
      PORT: 3002
    depends_on:
      - usuarios-db

  api-pagamentos:
    build: ./api-pagamentos
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgresql://user:pass@pagamentos-db:5432/pagamentos"
      MONGO_URL: "mongodb://user:pass@pedidos-db:27017/pedidos?authSource=admin"
      ORDER_API_URL: "http://api-pedidos:3004"
      PORT: 3003
    depends_on:
      - pagamentos-db
      - pedidos-db

  api-pedidos:
    build: ./api-pedidos
    ports:
      - "3004:3004"
    environment:
      MONGO_URL: "mongodb://user:pass@pedidos-db:27017/pedidos?authSource=admin"
      PORT: 3004
    depends_on:
      - pedidos-db
      - api-produtos
      - api-usuarios
  
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb-init/init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

    # === K6 ===
  k6:
    image: grafana/k6:latest
    container_name: k6_runner
    depends_on:
      - api-pagamentos
      - api-pedidos
      - influxdb
    volumes:
      - ./k6-scripts:/scripts
    entrypoint: ["k6"]
    networks:
      - default
  api-notifica:
    build: ./api-notifica
    container_name: api-notifica
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
    command: node ./index.js

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin


volumes:
  produtos_data:
  usuarios_data:
  pagamentos_data:
  pedidos_data:
  influxdb_data:
  grafana_data:
