version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: naouseadmin
      # POSTGRES_USER: usuario_postgres
      # POSTGRES_DB: senha_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  postgres_db_data:
    driver: local
  pgadmin_data:
    driver: local
